name: Run Android Samples
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    # run at 9AM & 9PM UTC
    - cron:  '0 9,21 * * *'

env:
  NDK_VERSION: 21.4.7075529

jobs:
  build:
    name: Swift toolchain for Android
    runs-on: macOS-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.0.1'
          #xcode-version: '13.3.1'

      - uses: actions/checkout@master

      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25b

      - name: Cache Homebrew
        uses: ./.github/actions/cache-always
        with:
          key: swift-android-homebrew-cache
          path: |
            /usr/local/Homebrew

      - name: Download dependencies
        run: |
          brew update
          brew install cmake ninja autoconf automake libtool pkg-config git-lfs wget curl gfortran android-platform-tools


